repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: clean-generated-artifacts
        name: clean generated artifacts
        entry: bash -c 'rm -rf ./build ./build-output'
        language: system
        pass_filenames: false

      - id: shfmt
        name: shfmt
        entry: nix develop --command shfmt -w scripts
        language: system
        files: ^scripts/.*\.sh$

      - id: task-test
        name: task test
        entry: nix develop --command task test
        language: system
        pass_filenames: false

      - id: actionlint
        name: actionlint
        entry: nix develop --command actionlint
        language: system
        files: ^\.github/workflows/.*\.(yml|yaml)$
