inputFiles:
  - ./templates/network.tmpl
  - ./templates/wireless.tmpl

outputFiles:
  - ./files/etc/config/network
  - ./files/etc/config/wireless

datasources:
  network:
    url: file:///tmp/network.yaml
  wireless:
    url: file:///tmp/wireless.yaml
