#!/bin/sh
set -e

/etc/init.d/cron enable || true
/etc/init.d/cron start || true

/etc/init.d/adguardhome enable || true
/etc/init.d/adguardhome start || true

/etc/init.d/tailscale enable || true
/etc/init.d/tailscale start || true

/etc/init.d/irqbalance enable || true
/etc/init.d/irqbalance start || true

/etc/init.d/odhcpd disable || true
/etc/init.d/odhcpd stop || true

exit 0
