network:
    map-e:
        vlan_id: ENC[AES256_GCM,data:W3KJ,iv:sLNlV7FuSOiK2w42ZUlBJp0cmbwAiPTnw2wic+/E0xY=,tag:MgEzDBtCDdWJcHmsKWLvBQ==,type:int]
        peeraddr: ENC[AES256_GCM,data:kfHY4HIbrMfxn/KQowYJaSkblCulRHpqm4+zrffVDeTgijk=,iv:b9G6I698KJnkfXHeOZGXJTSTzOUXJjX7VF6ZsgsPZMg=,tag:j07RjO+GY+T81ujWbrSr6w==,type:str]
        ipaddr: ENC[AES256_GCM,data:XmQen3T3ojs1rx9IuA==,iv:zxH7skOWsE7ML2EBOu67CXvMDXoA2sG7yBpqn3zs4s8=,tag:hsyc2FB3g/0ZkjiEA1FhBw==,type:str]
        ip6prefix: ENC[AES256_GCM,data:r+G7MDbzPVFpuHLz8CKKfsD5f/s=,iv:Yx/3zC03a9XASyQhusHgqCz0lsZVtzJ6EWTuDKBPDso=,tag:7pQ9u3QkeSBSdnN5EMExGQ==,type:str]
        ip6prefixlen: ENC[AES256_GCM,data:bFA=,iv:r2VoH8Hj/keWGiZemD5aFAowumAWmns2w6q3PSRY1jE=,tag:ySA+ut1MpIAvpGYXzKX/7g==,type:int]
    wireguard:
        server:
            endpoint: ENC[AES256_GCM,data:R9y3jI/kN0+9Ch+1ob44tn3pgQ==,iv:JlGtg+9qS+Goon6TcaMMb8bZobdxgo5Ek8kBEQsA4t4=,tag:eH4+s3AT/ON/GFwyCx+kpw==,type:str]
            private_key: ENC[AES256_GCM,data:ZwcU8ZQS+SglsbAJFPl87cY4WQUoUdOKBeeCWRD8dTGAfgx5nlffzMOnZ9g=,iv:9Vn2OU7Gv4YAT5v9l7ZEYrXQV/KdIAVAioG9AQTeMRc=,tag:/Lg8Sm9KSP1Jvf/LRn4xnw==,type:str]
        peers:
            - description: ENC[AES256_GCM,data:VQhiSdvs,iv:uyI+d10QCaAMhmHjzxc3wNZvcBM24Nh9p4Nw5g+asJM=,tag:eCgq+GyfSxzESWhPeduQQg==,type:str]
              public_key: ENC[AES256_GCM,data:XTrZDifimbt0Z6/rrMY35++9Qg7NJNfLVVQELJBsrxq2pZSyz3FbiMwv9Fo=,iv:GrYrk3NtY4DVTIhJ8gj6aVLbF9XrCt9McihAqPdhUcQ=,tag:HEZGPgQc3x1GK/FGzS5kUg==,type:str]
              preshared_key: ENC[AES256_GCM,data:ZF8JnSYBpRHkfTR6F/wBHsY+9fS1fais6kMEHapEn6L12/7blDeOaSe/9vY=,iv:vHCnETUVgNnTPNBunuYVauWkmZd5UbDAIM2k2luSTE0=,tag:GCue74fLMxxgYBimSYuRxg==,type:str]
              allowed_ip: ENC[AES256_GCM,data:fzME/B+0O7OukXapbw==,iv:VaGxwDfz8J8Q8Q5TbvsWoQ5HPa0MWD5VZgt6J1fziqA=,tag:jXkOsz1Bj+0wens3VjFNwg==,type:str]
            - description: ENC[AES256_GCM,data:F+KaHm8=,iv:mM4jXDr1AJ1l7ZN3KSTWwjdaG23mFAe2M88/wBSvP8c=,tag:br/lQ0yOa3vN01DVt4MbKQ==,type:str]
              public_key: ENC[AES256_GCM,data:oI+k+/rMqkhqGsvsEWRQp4fK4GKtIsYztzany2ErlzwKrpIm7xkKjVJYgOs=,iv:uamcv73YyXG+nSkJA9+T3YtSrNxOEG6ceuiyRqUHSo4=,tag:sJmYpPSI/WylqoQyEhnjqA==,type:str]
              preshared_key: ENC[AES256_GCM,data:HMdCyAzXZ546SywmdUVhcXssuX+L/AhuEMcAZWB+6j5bLSDgH8cgDeGw1uI=,iv:kTY1o3IYdVZJ9e37w2QLGRxSJbwkU0o5+HheI+YsLVA=,tag:77dY7X+7cR+7bB50N27nqA==,type:str]
              allowed_ip: ENC[AES256_GCM,data:scMZPFSnIwkNZjIICg==,iv:F4/DWXqEATt6NnUbNS9XgDsC1X1b0TtYSDoU5zQabmU=,tag:714NuPz+mNbgebKKbT70pw==,type:str]
            - description: ENC[AES256_GCM,data:CYSkWYKv,iv:Bk4DjLxc25Mjnag+GocwaKKdzRi/9MB6QYaHULLkgzM=,tag:DbpN7LWGsVEzJ+Qn2ywJaA==,type:str]
              public_key: ENC[AES256_GCM,data:PBeL6vpfeZ87hMnt50NaqYiRmtUYgViYi6hDel6KT35O+q7KcalUBVEtgy0=,iv:KXc3PI9CLNBskBIUN3IGySZYvjqiWyhU5G1pz30HpVA=,tag:CV2yzjy6dnBb6MWem6Qkjw==,type:str]
              preshared_key: ENC[AES256_GCM,data:B89IhJCsGGWmA2apHlnvRPSAmkMTHazVIVIw++L3PzKsRMeDgqpps6glPEM=,iv:S+H88P9wrWx0vZaIRPKXJW82+5EGQ4oQpkbkKjwIhg8=,tag:VCN+ZF6G5fa9PY6TVFSEBw==,type:str]
              allowed_ip: ENC[AES256_GCM,data:F98u1+Fdz707UyEOlQ==,iv:ctOyCzk7runw8aFlFur7XuJWRULbgqAHaekPvncDPhA=,tag:9/jG74hjOtOLBnhNk4+ZHw==,type:str]
wireless:
    wifi:
        name: ENC[AES256_GCM,data:Ld53P9Y=,iv:QW6paogoYXrGpoQ/QXqTw9nsmTGX5mI5+xcTmS1fjA0=,tag:BuKR31+6jh6V2gyx3Rf0Nw==,type:str]
        country: ENC[AES256_GCM,data:XFg=,iv:XGKrImuh67MGNP4Rjjg8icXPiUeQOodyg60lV647/xw=,tag:S2thWRfMyXwou5K5scP14A==,type:str]
        password:
            2g: ENC[AES256_GCM,data:UxOetoXRFlk28gYa,iv:kvMHuwxyH0jRmuJWBzevoqCW0ktY277qvmlz8iG2l4o=,tag:YVDwMoTa2Adh/XN1gjlI9w==,type:str]
            5g: ENC[AES256_GCM,data:cN1Lh/W6G4VeQLA9,iv:anFQXJQ/Ihvkii9hJKaM1Dt1hq87amJcMSokfYGNeXo=,tag:6X2NyOin8ndP2rnlMZx6gQ==,type:str]
adguardhome:
    user:
        name: ENC[AES256_GCM,data:qEKvPpc=,iv:s2gTy+ZOsueRqPzNnLus5BQIC9y5x150r+w8h1DuH6A=,tag:Lw0FIpEPDfynGXymTvJ+vA==,type:str]
        password_hash: ENC[AES256_GCM,data:CBOUWl32xbp5mnuHznOyLdo7K1ezEiqEHM08fLQjWTMZ/FEFYQsGMxX78A3P3dw9xwZDh6CMbAYVhI1X,iv:YJJKYRSUeDP4UrZy0Tf9L8Zt8tP1lr1aXTNfPIVyvHQ=,tag:jm6V2wtVjZ0mPFPTpXSnJw==,type:str]
sops:
    age:
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBjCf1PpvoMshFkoyjFOYUJ6/pLexwEFqr29COJawkoB
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDhvMTdTdyBHNVRU
            MFBjQkIzam9FZzR1UTJYUFRNMkhiOVVXVXRpdkN2Zy91QUoxOVRrCmpvck5NY3lV
            ODRXN2JLTGJ4TEhvVVY4KysvUmwrVEJYV1pNYUR3V2ZEMjAKLS0tIFRGeFQ5WmhS
            RlRGZzgzdkp4TmdtNHF5dThBYXh6ak1WSldldWpaVDQyTkkKgFVdqmHmMWF6a424
            afRxYUj8f+3fCitLJvSrfksogwN5cZKwo6kNGFybCnL+BFkqFbzPsMv3Ek3Lf2tx
            XephoQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-19T17:28:30Z"
    mac: ENC[AES256_GCM,data:ddjMffoHX+1LSvMGf61DZ9XyFdWbytoi7DUbujbglDH3YdKZLJ0ZOetHwK1vFuWFRR99ECMagHrY3+N58GRV15wHJqCzP3hpwtou2rvAelDEcGvNHeqiZchHpKH2K/AS9r7Wa0LfSTXUhHn+Wq17DCSlDvpxOK1mmrSRzokh+xE=,iv:CqWwReWpe2HMJtzXt4fC6bb8Xd2mbo1nEzJT3nDC1uE=,tag:r/8tFt8FgG0VNNLAcQfZDg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
