name: Check

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  nix:
    name: Nix flake check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.0

      - name: Install Nix
        uses: cachix/install-nix-action@v31.10.6

      - name: Run checks
        run: nix flake check --print-build-logs
