name: Lint

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  shell:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Task
        uses: go-task/setup-task@v1

      - name: Install shellcheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck

      - name: Run shell lint
        run: task lint
